# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 704f30f89da023fbbf3365802a8d2cc245ac539b6cbce533eeaa8d8b9dbddbc302557e7e2c085683278e667a5c0e677a3e8f611f295a61a5c79e6dd035cc1a4a

test:
  secret_key_base: cc0d5b6c773fb3d2131f943f61651a3bcc6392cd58524ffb02199d0148595d73c80e1d70463d48265e8aea7ce8d067ef5a167b40113c10e67103c5c47b642e5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
